
// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

// TODO: Replace with your actual Firebase project configuration
const firebaseConfig = {
  apiKey: "AIzaSyCkg5lVp22_TmQOKYtkT8tsJW94Sd3fB5o",
  authDomain: "savagemath.firebaseapp.com",
  projectId: "savagemath",
  storageBucket: "savagemath.firebasestorage.app",
  messagingSenderId: "460962338541",
  appId: "1:460962338541:web:c7731c5fbd8873412b5ee4"
};

// Initialize Firebase
let app;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

const db = getFirestore(app);

export { db };
